---
title: "Stream Data"
author: "Haylee Oyler"
format: html
editor: source
execute:
  warning: false
  message: false
editor_options: 
  chunk_output_type: console
---

#### Setup

```{r}
library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(skimr)
library(patchwork)
```

## Set wd and read in data
```{r}
setwd("/courses/EDS214/group_project/2024/team-mojo-jojo/raw_data")

BQ1 <- read_csv("/courses/EDS214/group_project/2024/team-mojo-jojo/raw_data/QuebradaCuenca1-Bisley.csv")
BQ2 <- read_csv("QuebradaCuenca2-Bisley.csv")
BQ3 <- read_csv("QuebradaCuenca3-Bisley.csv")
PRM <- read_csv("RioMameyesPuenteRoto.csv")
```

## Clean data
```{r}
# Clean data frame names and date
BQ1 <- BQ1 %>% 
  clean_names() %>% 
  mutate(date = ymd(sample_date)) 

BQ2 <- BQ2 %>% 
  clean_names() %>% 
  mutate(date = ymd(sample_date)) 

BQ3 <- BQ3 %>% 
  clean_names() %>% 
  mutate(date = ymd(sample_date)) 

PRM <- PRM %>% 
  clean_names() %>% 
  mutate(date = ymd(sample_date),
         sample_id = str_replace_all(sample_id, "MPR", "PRM")) 

```

```{r}
# Bind the data frames together 
BQ12 <- rbind(BQ1, BQ2)
BQ3PRM <- rbind(BQ3, PRM)

stream_df <- rbind(BQ12, BQ3PRM)
```

## Explore data

```{r}
summary(stream_df)
names(stream_df)
skim(stream_df)
```

## Plot data
```{r}
plot1_df <- stream_df %>% 
  select(date, k, no3_n, sample_id) %>% 
  mutate(year = year(date)) %>% 
  # filter(year >= 1988 & year <= 1994)
  filter(year %in% 1988:1994)

kplot <- plot1_df %>% 
  filter(date %in% ymd("1988-10-01"):ymd("1992-03-01"))
```

### Potassium Plot
```{r}
ggplot(kplot, aes(x = date, y = k)) + 
  geom_smooth(span = 0.2, aes(linetype = sample_id), 
              alpha = 0.001, color = "black", linewidth = 0.6) +
  scale_x_date(position = "top", date_breaks = "12 months", 
               date_labels = "%Y", date_minor_breaks = "2 months", 
               limits = c(ymd("1987-10-01"), ymd("1994-08-01"))) +
  scale_y_continuous(breaks = c(0.4, 0.7, 1.0, 1.3, 1.6)) +
  labs(x = "Years") +
  ylab(bquote("K mgl^-1")) +
  geom_vline(xintercept = ymd("1989-09-17"), linetype = 2) +
  theme(panel.background = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(.90, .80),
        legend.title = element_blank(),
        legend.key = element_blank(),
        text = element_text(size = 14, family = "sans serif", face = "bold"),
        legend.text = element_text(size = 16))

# This works to set the date range we want, but it adjust the axis scale
# limits = c(ymd("1987-10-01"), ymd("1994-03-01"))

# seq(from = 0.4, to = 1.6, by = 0.2)
#legend.position = c(ymd("1993-06-01"), 1.45)
```

### Nitrate plot
```{r}
ggplot(plot1_df, aes(x = date, y = no3_n)) +
  geom_smooth(span = 0.2, aes(linetype = sample_id), 
              alpha = 0.001, color = "black", linewidth = 0.6, 
              show.legend = FALSE) +
  scale_x_date(date_breaks = "12 months", 
               date_minor_breaks = "2 months", 
               limits = c(ymd("1987-10-01"), ymd("1994-08-01"))) +
  scale_y_continuous(breaks = c(5, 100, 300, 500)) +
  ylab(bquote("NO[3]-N µgl^-1")) +
  geom_vline(xintercept = ymd("1989-09-17"), linetype = 2) +
  theme(axis.text.x=element_blank(),
        axis.title.x = element_blank(),
        panel.background = element_blank(),
        axis.text = element_text(colour = "black"),
        text = element_text(size = 14, family = "sans serif", face = "bold"))
```

### Combined plot
```{r}
p1 <- ggplot(kplot, aes(x = date, y = k)) + 
  geom_smooth(span = 0.1, aes(linetype = sample_id), 
              alpha = 0.001, color = "black", linewidth = 0.6) +
  scale_x_date(position = "top", date_breaks = "12 months", 
               date_labels = "%Y", date_minor_breaks = "2 months", 
               limits = c(ymd("1988-01-01"), ymd("1994-08-01"))) +
  scale_y_continuous(breaks = c(0.4, 0.7, 1.0, 1.3, 1.6)) +
  labs(x = "Years") +
  ylab(bquote("K mgl^-1")) +
  geom_vline(xintercept = ymd("1989-09-17"), linetype = 2) +
  theme(panel.background = element_blank(),
        axis.text = element_text(colour = "black"),
        axis.ticks.x = element_line(color = "green"),
        legend.position = c(.80, .55),
        legend.title = element_blank(),
        legend.key = element_blank(),
        legend.key.size = unit(1.4, 'cm'),
        text = element_text(size = 14, 
                            family = "sans serif", 
                            face = "bold"),
        legend.text = element_text(size = 16))

p2 <- ggplot(plot1_df, aes(x = date, y = no3_n)) +
  geom_smooth(span = 0.1, aes(linetype = sample_id), 
              alpha = 0.001, color = "black", linewidth = 0.6, 
              show.legend = FALSE) +
  scale_x_date(date_breaks = "12 months", 
               date_minor_breaks = "2 months", 
               limits = c(ymd("1988-01-01"), ymd("1994-08-01"))) +
  scale_y_continuous(breaks = c(5, 100, 300, 500)) +
  ylab(bquote("NO[3]-N µgl^-1")) +
  geom_vline(xintercept = ymd("1989-09-17"), linetype = 2) +
  theme(axis.text.x=element_blank(),
        axis.title.x = element_blank(),
        panel.background = element_blank(),
        axis.text = element_text(colour = "black"),
        text = element_text(size = 14, family = "sans serif", face = "bold"))

p1 / p2  & theme(plot.margin = margin(5, 0, 0, 10),
                plot.background = element_rect(fill = "white"),
                panel.background = element_rect(fill = "white"), 
                panel.border = element_rect(color = "black", fill = NA))
```
