---
title: "Team Mojo Jojo"
author: "IMS"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
```
/courses/EDS214/group_project/2024/team-mojo-jojo

```{r}
#read in the data 
sites_id <- c( "Q1",  "Q2",  "Q3",  "QG",  
              "QPA", "QPB",  "QP",  "QS", 
               "QT",  "RI",  "MG", "MPR")

filenames = dir("/courses/EDS214/group_project/2024/team-mojo-jojo/raw_data/", pattern="*.csv")

for (i in seq_along(filenames)){
  assign(sites_id[i], 
         read_csv(paste0("/courses/EDS214/group_project/2024/team-mojo-jojo/raw_data/",
                         filenames[i])
                  )
         )
}

site_elevation = data.frame(Sample_ID = c( "QS",  "QT",  "RI",  "MG",  
                                           "Q1",  "Q2",  "Q3", "QPA", 
                                          "QPB",  "QP", "MPR",  "QG"),
                            elevation = c(  326,   270,   620,    22, 
                                            218,   218,   198,   672, 
                                            662,   444,   140,   640)
)

cleaning_stuff <- function(i){
  get(i) |>
      left_join(get(i), site_elevation, join_by("Sample_ID")) |> 
      clean_names() |>
      mutate(date=ymd(sample_date),
             year=year(sample_date)) |>
      filter(year>=1988 & year<=1994)

}

for (i in sites_id){
  cleaning_stuff(i)
}


BQ1 <- BQ1 |> 
  clean_names() |> 
  mutate(date=ymd(sample_date))

```

```{r}
#Q1
Q1 <- left_join(Q1, site_elevation, join_by("Sample_ID"))

#Q2
Q2 <- left_join(Q2, site_elevation, join_by("Sample_ID"))

#Q3 
Q3 <- left_join(Q3, site_elevation, join_by("Sample_ID"))

#QG
QG <- left_join(QG, site_elevation, join_by("Sample_ID"))

#QP
QP <- left_join(QP, site_elevation, join_by("Sample_ID"))

#QPA
QPA <- left_join(QPA, site_elevation, join_by("Sample_ID"))

#QPB
QPB <- left_join(QPB, site_elevation, join_by("Sample_ID"))

#QS
QS <- left_join(QS, site_elevation, join_by("Sample_ID"))

#QT
QT <- left_join(QT, site_elevation, join_by("Sample_ID"))

#RI
RI <- left_join(RI, site_elevation, join_by("Sample_ID"))

#MG
MG <- left_join(MG, site_elevation, join_by("Sample_ID"))

#MPR
MPR <- left_join(MPR, site_elevation, join_by("Sample_ID"))


```

```{r}
# bind data together 
all_sites_df <- do.call("rbind", list(Q1, Q2, Q3, Q3, QG, QP, MG, MPR, QPA, QPB, QS, QT, RI))
unique(all_sites_df$Sample_ID)

graph_all <- all_sites_df |> 
  select(Sample_ID, `PO4-P`, `NO3-N`, elevation, K)

summary(graph_all)
```



